# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://fangsfdavid.github.io/pymeridian/"

git_url = "https://github.com/fangsfdavid/pymeridian/tree/{branch}/"

def custom_doc_links(name): return None
